'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WinNUT_Client.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Public ReadOnly Property _1025() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("1025", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Public ReadOnly Property _1026() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("1026", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Public ReadOnly Property _1028() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("1028", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Public ReadOnly Property _1032() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("1032", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Public ReadOnly Property _1040() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("1040", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Public ReadOnly Property _1057() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("1057", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Public ReadOnly Property _1058() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("1058", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Public ReadOnly Property _1060() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("1060", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Public ReadOnly Property _1064() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("1064", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Public ReadOnly Property _1072() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("1072", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Public ReadOnly Property _1079() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("1079", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Public ReadOnly Property _1080() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("1080", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Public ReadOnly Property _1092() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("1092", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Public ReadOnly Property _1096() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("1096", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Public ReadOnly Property _1104() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("1104", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Public ReadOnly Property _1121() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("1121", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Public ReadOnly Property _1122() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("1122", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Public ReadOnly Property _1124() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("1124", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Public ReadOnly Property _1128() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("1128", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Public ReadOnly Property _1136() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("1136", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Public ReadOnly Property _1152() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("1152", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Public ReadOnly Property _1216() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("1216", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Public ReadOnly Property _1280() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("1280", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Public ReadOnly Property _1344() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("1344", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Public ReadOnly Property _2001() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("2001", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Public ReadOnly Property _2002() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("2002", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Application shut down at.
        '''</summary>
        Public ReadOnly Property App_Event_Str_01() As String
            Get
                Return ResourceManager.GetString("App_Event_Str_01", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Battery_Charged() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Battery_Charged", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Battery_Charging() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Battery_Charging", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Battery_Discharging() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Battery_Discharging", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Delete_LogFile_24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Delete_LogFile_24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Old ups.ini imported
        '''Ini File Moved to {0}.old.
        '''</summary>
        Public ReadOnly Property Frm_Main_Str_01() As String
            Get
                Return ResourceManager.GetString("Frm_Main_Str_01", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Old ups.ini imported.
        '''</summary>
        Public ReadOnly Property Frm_Main_Str_02() As String
            Get
                Return ResourceManager.GetString("Frm_Main_Str_02", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Reconnection In Progress.
        '''</summary>
        Public ReadOnly Property Frm_Main_Str_03() As String
            Get
                Return ResourceManager.GetString("Frm_Main_Str_03", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Try {0} of {1}.
        '''</summary>
        Public ReadOnly Property Frm_Main_Str_04() As String
            Get
                Return ResourceManager.GetString("Frm_Main_Str_04", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Not Connected.
        '''</summary>
        Public ReadOnly Property Frm_Main_Str_05() As String
            Get
                Return ResourceManager.GetString("Frm_Main_Str_05", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Connected.
        '''</summary>
        Public ReadOnly Property Frm_Main_Str_06() As String
            Get
                Return ResourceManager.GetString("Frm_Main_Str_06", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à On Line.
        '''</summary>
        Public ReadOnly Property Frm_Main_Str_07() As String
            Get
                Return ResourceManager.GetString("Frm_Main_Str_07", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à On Battery ({0}%).
        '''</summary>
        Public ReadOnly Property Frm_Main_Str_08() As String
            Get
                Return ResourceManager.GetString("Frm_Main_Str_08", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Low Battery.
        '''</summary>
        Public ReadOnly Property Frm_Main_Str_09() As String
            Get
                Return ResourceManager.GetString("Frm_Main_Str_09", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Battery OK.
        '''</summary>
        Public ReadOnly Property Frm_Main_Str_10() As String
            Get
                Return ResourceManager.GetString("Frm_Main_Str_10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Unknown UPS Name.
        '''</summary>
        Public ReadOnly Property Frm_Main_Str_11() As String
            Get
                Return ResourceManager.GetString("Frm_Main_Str_11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Lost Connect To {0}:{1}.
        '''</summary>
        Public ReadOnly Property Frm_Main_Str_12() As String
            Get
                Return ResourceManager.GetString("Frm_Main_Str_12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Wrong Login ID (Username or Password).
        '''</summary>
        Public ReadOnly Property Frm_Main_Str_13() As String
            Get
                Return ResourceManager.GetString("Frm_Main_Str_13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Restarting WinNUT after waking up from Windows..
        '''</summary>
        Public ReadOnly Property Frm_Main_Str_14() As String
            Get
                Return ResourceManager.GetString("Frm_Main_Str_14", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Windows standby. WinNUT will disconnect..
        '''</summary>
        Public ReadOnly Property Frm_Main_Str_15() As String
            Get
                Return ResourceManager.GetString("Frm_Main_Str_15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Battery_Charge : {0}
        '''Remaining Time : {1}.
        '''</summary>
        Public ReadOnly Property Frm_Shutdown_Str_01() As String
            Get
                Return ResourceManager.GetString("Frm_Shutdown_Str_01", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Update Available : Version {0}.
        '''</summary>
        Public ReadOnly Property Frm_Update_Str_01() As String
            Get
                Return ResourceManager.GetString("Frm_Update_Str_01", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Show ChangeLog.
        '''</summary>
        Public ReadOnly Property Frm_Update_Str_02() As String
            Get
                Return ResourceManager.GetString("Frm_Update_Str_02", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Hide ChangeLog.
        '''</summary>
        Public ReadOnly Property Frm_Update_Str_03() As String
            Get
                Return ResourceManager.GetString("Frm_Update_Str_03", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Update WinNUT-Client Now?
        '''Ok to Close WinNut and Install New Version
        '''Cancel to Save Msi and Install Later.
        '''</summary>
        Public ReadOnly Property Frm_Update_Str_04() As String
            Get
                Return ResourceManager.GetString("Frm_Update_Str_04", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Download New Version from :.
        '''</summary>
        Public ReadOnly Property Frm_Update_Str_05() As String
            Get
                Return ResourceManager.GetString("Frm_Update_Str_05", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à https://github.com/gawindx/WinNUT-Client.
        '''</summary>
        Public ReadOnly Property GitHub_URL() As String
            Get
                Return ResourceManager.GetString("GitHub_URL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à WinNut Preferences Changed.
        '''</summary>
        Public ReadOnly Property Log_Str_01() As String
            Get
                Return ResourceManager.GetString("Log_Str_01", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Connection to Nut Host {0}:{1} Established.
        '''</summary>
        Public ReadOnly Property Log_Str_02() As String
            Get
                Return ResourceManager.GetString("Log_Str_02", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Connection to Nut Host {0}:{1} Failed: {2}.
        '''</summary>
        Public ReadOnly Property Log_Str_03() As String
            Get
                Return ResourceManager.GetString("Log_Str_03", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Automatic Reconnection.
        '''</summary>
        Public ReadOnly Property Log_Str_04() As String
            Get
                Return ResourceManager.GetString("Log_Str_04", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Disconnected from Nut Host.
        '''</summary>
        Public ReadOnly Property Log_Str_05() As String
            Get
                Return ResourceManager.GetString("Log_Str_05", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Try Reconnect {0} / {1}.
        '''</summary>
        Public ReadOnly Property Log_Str_06() As String
            Get
                Return ResourceManager.GetString("Log_Str_06", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Max Retry reached. Wait for manual Reconnection.
        '''</summary>
        Public ReadOnly Property Log_Str_07() As String
            Get
                Return ResourceManager.GetString("Log_Str_07", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Conditions met for launching the Extinguishing Process.
        '''</summary>
        Public ReadOnly Property Log_Str_08() As String
            Get
                Return ResourceManager.GetString("Log_Str_08", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Cancellation of the Extinguishing Process.
        '''</summary>
        Public ReadOnly Property Log_Str_09() As String
            Get
                Return ResourceManager.GetString("Log_Str_09", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à No Update Available.
        '''</summary>
        Public ReadOnly Property Log_Str_10() As String
            Get
                Return ResourceManager.GetString("Log_Str_10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Version {0} Available.
        '''</summary>
        Public ReadOnly Property Log_Str_11() As String
            Get
                Return ResourceManager.GetString("Log_Str_11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Stop condition imposed by the NUT server.
        '''</summary>
        Public ReadOnly Property Log_Str_12() As String
            Get
                Return ResourceManager.GetString("Log_Str_12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property ups_104x104() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ups_104x104", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property ViewLogFile_24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ViewLogFile_24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Public ReadOnly Property WinNut() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("WinNut", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Public ReadOnly Property WinNUT_Updater() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("WinNUT_Updater", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
    End Module
End Namespace
